# Generated by Django 4.2.4 on 2023-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='listing_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
