# Generated by Django 4.2.4 on 2023-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('Dolnośląskie', 'Lower Silesia'), ('Kujawsko-Pomorskie', 'Kuyavia-Pomerania'), ('Lubelskie', 'Lublin'), ('Lubuskie', 'Lubusz'), ('Łódzkie', 'Lodzkie'), ('Małopolskie', 'Lesser Poland'), ('Mazowieckie', 'Masovia'), ('Opolskie', 'Opole'), ('Podkarpacke', 'Subcartpathian'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomerania'), ('Śląskie', 'Silesia'), ('Świętokrzyskie', 'Holy Cross'), ('Warmińsko-Mazurskie', 'Warmia-Masuria'), ('Wielkopolskie', 'Greater Poland'), ('Zachodniopomorskie', 'West Pomerania')]),
        ),
    ]
