# Generated by Django 4.2.4 on 2023-10-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('Lower Silesia', 'Lower Silesia'), ('Kuyavia-Pomerania', 'Kuyavia-Pomerania'), ('Lublin', 'Lublin'), ('Lubusz', 'Lubusz'), ('Lodzkie', 'Lodzkie'), ('Lesser Poland', 'Lesser Poland'), ('Masovia', 'Masovia'), ('Opole', 'Opole'), ('Subcartpathian', 'Subcartpathian'), ('Podlaskie', 'Podlaskie'), ('Pomerania', 'Pomerania'), ('Silesia', 'Silesia'), ('Holy Cross', 'Holy Cross'), ('Warmia-Masuria', 'Warmia-Masuria'), ('Greater Poland', 'Greater Poland'), ('West Pomerania', 'West Pomerania')]),
        ),
    ]
